In [1]:
import json
import gzip
import os
from os import path
import pandas as pd
import numpy as np
import datetime
import plotly.express as px 
import plotly.graph_objects as go
from IPython.core.display import display, HTML
from collections import defaultdict
import pickle

In [2]:
def is_json(myjson):
    try:
        json_object = json.loads(myjson)
    except ValueError as e:
        return False
    return True

def read_data(path):
    data = []
    with open(path, errors='ignore') as f:
        for line in f.readlines():
            try: 
                if not is_json(line):
                    continue
                data.append(json.loads(line))
            except:
                print('bad json: ', line)
    return data

In [3]:
def draw_graph(df, feature, name, title):
    html_path = "https://harmony-one.github.io/harmony-log-analysis/" + html_dir.replace("../../docs/", "")
    
    hover = df.columns.tolist()
    fig = px.line(df, x='date', y=feature, color_discrete_sequence = ['#99d6ff'], title = 'Harmony {} Chart'.format(title))

    fig.update_xaxes({'showgrid': False, 'showspikes': True, 'title': None})
    fig.update_yaxes({'gridcolor': "#E8E8E8"})
    fig.update_layout({'plot_bgcolor':'rgba(0,0,0,0)', "title_x": 0.5, 'hovermode': 'closest'})
#     fig.show(renderer="svg",width=800, height=500)
    fig.write_html("{:s}{:s}.html".format(html_dir, name))
    print("HTML saved in " )
    display_path = "{:s}{:s}.html".format(html_path, name)
    display(HTML("<a href='" + display_path + "' target='_blank'>" + display_path + "</a>"))
    return fig

In [4]:
html_dir = "../../../docs/graphs/transparency_report/"
if not path.exists(html_dir):
    try:
        os.makedirs(html_dir)
    except:
        print("Could not make directory")
        exit(1)

In [ ]:
path = "../logs/blockchain_0.log"
gas = read_data(path)

In [19]:
gas_df = pd.DataFrame(gas)

In [20]:
gas_df.to_csv("../csv/gas_0.csv", index = False)

In [21]:
gas_df['timestamp'] = pd.to_datetime(gas_df['timestamp'], format = '%Y_%m_%d %H:%M:%S')
gas_df['date'] = gas_df['timestamp'].dt.date

In [11]:
gas_limit = gas_df.groupby(['date'])['gasLimit'].mean().reset_index(name = 'gasLimit')
gas_limit.to_csv("../csv/gas_limit_0.csv", index = False)

In [14]:
gas_used = gas_df.groupby(['date'])['gasUsed'].sum().reset_index(name = 'gasUsed')
gas_used.to_csv("../csv/gas_used_0.csv", index = False)

In [16]:
size = gas_df.groupby(['date'])['size'].sum().reset_index(name = 'size')
size.to_csv("../csv/size_0.csv", index = False)

In [17]:
gas_df

,timestamp,shard,block,gasLimit,gasUsed,size,date
0,2020-02-18 18:05:09,1,199,80000000,0,737,2020-02-18
1,2020-02-18 18:05:34,1,2364556,80000000,0,737,2020-02-18
2,2020-02-18 18:05:25,1,2364555,80000000,0,737,2020-02-18
3,2020-02-18 18:05:50,1,2364558,80000000,0,737,2020-02-18
4,2020-02-18 18:05:58,1,2364559,80000000,0,737,2020-02-18
...,...,...,...,...,...,...,...
9525819,2020-07-17 05:54:11,3,3967575,80000000,0,708,2020-07-17
9525820,2020-07-17 05:54:19,3,3967576,80000000,0,708,2020-07-17
9525821,2020-07-17 05:54:27,3,3967577,80000000,0,708,2020-07-17
9525822,2020-07-17 05:54:35,3,3967578,80000000,0,708,2020-07-17
9525823,2020-07-17 05:54:43,3,3967579,80000000,0,708,2020-07-17